### ISSUE TITLE
Dataset download

### ISSUE THREAD

**Issue by phquentin** [xingyul/stereobj-1m#2]
Hi,
I'm having trouble downloading your dataset. It seems that your link is disabled, probably due to bandwidth limitations of DropBox?
![image](https://user-images.githubusercontent.com/44317030/223816785-753d5134-ac67-49e6-9d79-f9eae39535c1.png)

**Comment by xingyul** [comment]
Hi,

Are you still having problem downloading the data? I currently have no problem downloading it, even after signing out of my own Dropbox account.

If you are still experiencing the same error, maybe try to download again in a few days?

**Comment by z7r7y7** [comment]
Hello，
I ran into the same problem when downloading the dataset，the Dropbox link provided appears to be inactive or expired, preventing me from accessing the dataset files.

I have tried accessing the dataset on multiple occasions, but the link consistently returns an error indicating that it is no longer available. I believe this may be due to the link being shared or downloaded excessively within a short period of time. I was wondering if there is an alternative way to access the dataset or if the link can be updated. I would greatly appreciate your assistance in resolving this matter.

**Comment by xingyul** [comment]
@z7r7y7 @phquentin  Thanks for reaching out for this issue. It seems that the subscribed plan for our Dropbox account has expired. That's why the download link is disabled. I have contacted our lab admin to make the payment and renew the subscribed plan. But she wouldn't be able to do so until next Monday. I'll update with you guys once the plan is renewed and the download link is working again.

Thanks for bringing this to my attention and thanks for your patience in waiting.

**Comment by xingyul** [comment]
Hi @z7r7y7 @phquentin, the download link should be working again. Thanks for bringing this issue to my attention. This issue is closed now.
